### ISSUE TITLE
Search buttons

### ISSUE THREAD

**Issue by Finnegan5** [alma-farm/alma#485]
idk if it’s supposed to be like this, but it seems wrong.

![639ECC5A-C852-4330-B98D-36444982B331](https://user-images.githubusercontent.com/57829782/87567583-b58c9380-c6c4-11ea-987d-2d1ff846b89b.jpeg)

![63F47B6B-45C9-4BED-930D-66FD4F47557B](https://user-images.githubusercontent.com/57829782/87567595-bcb3a180-c6c4-11ea-859c-3cdf2f65446d.jpeg)

**Comment by patplue** [comment]
@Finnegan5 i cant reproduce this so i dont know how to fix it

**Comment by Finnegan5** [comment]
![4925E966-12AA-43D7-9B12-5A24D89F777C](https://user-images.githubusercontent.com/57829782/89924672-a5ec6600-dc02-11ea-8f86-2b8dea102ede.jpeg)

What about this kinda style?

**Comment by patplue** [comment]
that how it actually looks everywhere except on your iphone lol
