### ISSUE TITLE
Producer Show load map

### ISSUE THREAD

**Issue by Finnegan5** [alma-farm/alma#488]
![52D30715-5A4F-40F3-87C7-4DE7DD82C03C](https://user-images.githubusercontent.com/57829782/87567985-39df1680-c6c5-11ea-8029-7f463742731d.jpeg)

**Comment by patplue** [comment]
@Finnegan5 since this button is generated by the js method that handles map consent i think it just gets overwritten on mobile since it works perfectly fine on desktop

**Comment by Finnegan5** [comment]
Could u maybe make it a link then, so you don’t get the webkit styling?
