### ISSUE TITLE
Bottom menu with obsolete modals

### ISSUE THREAD

**Issue by Finnegan5** [alma-farm/alma#490]
![92C73849-6B7B-4CF4-8422-642C3CB328E5](https://user-images.githubusercontent.com/57829782/87568180-875b8380-c6c5-11ea-8e1d-6fca8cc38609.png)

**Comment by patplue** [comment]
So you want me to remove the modal since you say its obsolete so we link directly to the cart?

**Comment by Finnegan5** [comment]
Yeah, that’s what I thought .
